apiVersion: v1
kind: ConfigMap
metadata:
  name: t2
  labels:
    env: test
data:
  example.property: "hello"
  another.property: "world"
---
apiVersion: v1
kind: Service
metadata:
  name: s2
  labels:
    env: test
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080